"""Render fixed C++ harness code. No model-authored C++ is executed as a test."""
import json


def render_testbench(contract, vectors):
    params = contract['inputs']
    fields = '\n'.join(f'    long long v{i};' for i in range(len(params)))
    rows = '\n'.join('    {' + ', '.join(str(v) + 'LL' for v in row['inputs'] + [row['expected']]) + '},' for row in vectors)
    args = ', '.join(f'static_cast<{p["type"]}>(c.v{i})' for i, p in enumerate(params))
    return f'''// Generated by agent.selftest. Proposed oracle, not an official test.
#include "interface.h"
#include <iostream>
struct SelftestVector {{
{fields}
    long long expected;
}};
static const SelftestVector selftest_vectors[] = {{
{rows}
}};
int main() {{
    unsigned failures = 0;
    const unsigned count = sizeof(selftest_vectors) / sizeof(selftest_vectors[0]);
    for (unsigned i = 0; i < count; ++i) {{
        const SelftestVector &c = selftest_vectors[i];
        long long actual = static_cast<long long>({contract['top_function']}({args}));
        std::cout << "SELFTEST_CASE {{\\"case_id\\":" << i
                  << ",\\"actual\\":" << actual << "}}" << std::endl;
        if (actual != c.expected) ++failures;
    }}
    std::cout << "SELFTEST_END {{\\"count\\":" << count
              << ",\\"failures\\":" << failures << "}}" << std::endl;
    return failures ? 1 : 0;
}}
'''


def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + '\n'
